version: "3"

services:
  generator:
    container_name: generator
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file:
    - .env
    ports:
    - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
    - redis

  redis: 
    container_name: generator_redis
    image: redis
    restart: always
    env_file:
    - .env

networks:
  default:
    driver: bridge